version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - /var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scrape_sample
    ports:
      - "127.0.0.1:5432:5432"